### ISSUE TITLE
[Challenge Request] nested forms

### ISSUE THREAD

**Issue by tomer953** [tomalaforge/angular-challenges#176]
A common task for any web developer is to build forms, some of them are more than just a simple “login” form.

Lets take an example of creating “Create new Challenge” form, with 3 parts:
- Basic info:  name, description, difficulty
- author details: name, age, socialUrl
- references: array of useful urls

Now the aim of the challenge is to:
1. Split the form logic into smaller components, while still be able to maintain the form state (valid \ etc)
2. Maintain the form type, using strongly typed forms
3. Be able to reuse the smaller components in different context, such as “edit address” dialog 

I think strongly typed forms is a bit tricky when trying to split into components.
What do you think about the idea?

**Comment by tomalaforge** [comment]
Hello Tomer, 

You are on fire and I like that. Thanks you for proposing a challenge. you are the first one. 🙏

I was going to create challenges on forms as well, so this is a torific idea. 

The goal is to make small challenges. From my experience, if challenges are too complex or take too much time, nobody will do them.  

But I think, this should be a good one. But hard one I suppose, you'll decide that later.

On form there is a lot we can do:
- for beginner: create simple form
- validators
- async validartors
- validators on multiple fields
- error handling
- and so on 😅

I think you can create your challenge in a sub-folder called forms

If you have any questions, you know where to find me 💪

**Comment by tomer953** [comment]
Yes I get your point. 

Imo, basic forms, basic validations, and the stuff you mentioned its too easy/basic so it's the hello world of reactive forms and evolved no real challenge.

However, strongly type forms is kinda new, and nested/reusable  forms has like 20 different solutions. its very interesting to see solutions for it. 

Of course I personally prefer you to create it, since I want to test my solution as well. 
but I'll glad to help if needed. 

ps, DMing you on X is not allowed.

**Comment by tomalaforge** [comment]
Yes I get it: basic form and validation is like the hello word of forms but the goal is not only to create hard and difficult challenge but it's also a place to learn and practise (even for beginners). But I get your point. It's better to challenge yourself on not day-to-day work. Having a mix of both is good. Some people wants to land their first job, other wants to progress, other wants to challenge themself. Hard to satisfied everyone.

I see what I can do but this will not be for now. I want to finish my serie on performance. I still have two challenges.

**Comment by tomalaforge** [comment]
and DM should be open. Was open to verified account only. 😅

**Comment by Brack0** [comment]
Hi Tomer, hi Thomas 👋 ,

Maybe we can also create a "easy" challenge on forms with a problem like this. So that people learning Angular can have fun too. This challenge can be a good first step to help solve more complex problems later, such as nested typed forms.

---

### ControlValueAccessor

#### Information

Give some insight on forms, reactive forms and reusable parts of forms.

Link to ControlValueAccessor (https://angular.dev/api/forms/ControlValueAccessor)

#### Statements

You start with this form (ref: https://angular.dev/guide/forms/reactive-forms#grouping-form-controls).
```ts
import { Component } from "@angular/core";
import {
  FormGroup,
  FormControl,
  FormsModule,
  ReactiveFormsModule,
} from "@angular/forms";

@Component({
  standalone: true,
  imports: [FormsModule, ReactiveFormsModule],
  selector: "app-root",
  template: `
    <form [formGroup]="profileForm">
      <label for="first-name">First Name: </label>
      <input id="first-name" type="text" formControlName="firstName" />
      <label for="last-name">Last Name: </label>
      <input id="last-name" type="text" formControlName="lastName" />
    </form>
  `,
})
export class AppComponent {
  profileForm = new FormGroup({
    firstName: new FormControl(""),
    lastName: new FormControl(""),
  });
}
```

Wrap label and input in a reusable component.

#### Constraints

- The component must be compatible with formControlName
- The logic inside the parent component must remain the same

**Comment by tomalaforge** [comment]
Yes that's a very good idea. Do you want to do it ?

**Comment by Brack0** [comment]
Sure, PR incoming soon.
