### ISSUE TITLE
challenge 11: typo in doc and config error in 

### ISSUE THREAD

**Issue by rd003** [tomalaforge/angular-challenges#224]
Hi ,
 
- There is typo in doc, please update this typo from `npx nx serve rxjs-pipe-bu` to `npx nx serve rxjs-pipe-bug`.
- I am also facing error when running this command `NX   Could not find any runner configurations in nx.json`.
  I have restarted the vs code and run the serve command again. Now i am getting different error: ` NX   Cannot read properties of undefined (reading 'default')`. 

doc url: https://angular-challenges.vercel.app/challenges/rxjs/11-bug-chaining-operator/

**Comment by rd003** [comment]
`NX   Cannot read properties of undefined (reading 'default')`

getting this error on serving every project. I have taken latest changes from upstream and my main repo is completely sync with upstream. Still getting the error.

**Comment by tomalaforge** [comment]
I upgraded the project to Nx17, you need to do a `npm ci`

If that doesn't work, delete your node module `rm -rf node_module` and rerun `npm ci` and everything should work as expected

**Comment by tomalaforge** [comment]
@rd003 did it solve your pb?

**Comment by rd003** [comment]
I haven't tried it. Thanks for quick reply. I will notify you as soon as possible.

**Comment by rd003** [comment]
is `npm ci` a platform specific command. I use windows machine.
I am getting the error while running `npm ci`
`The operation was rejected by your operating system.`

**Comment by tomalaforge** [comment]
What is your node version : `node -v` and npm version: `npm --version`

**Comment by rd003** [comment]
18.13.0

**Comment by rd003** [comment]
should i update it to node 20

**Comment by tomalaforge** [comment]
and your version of npm?

**Comment by rd003** [comment]
node: 18.13.0
npm: 9.8.1

**Comment by tomalaforge** [comment]
you can try to update both 
I'm on node: v20.8.1
npm: 10.2.0

did you try to delete your node_module? rm -rf node_modules

**Comment by rd003** [comment]
No...i haven't deleted node_modules.
Now i know that i have to upgrade to nx 17.

I will follow your instructions,but due to some reasons I can't do it right
now.
Thanks for responding. I will inform you soon..

**Comment by rd003** [comment]
Hi Thomas,

I have followed the steps you have provided. I've deleted node modules, upgraded node and npm. 
Reinstalled packages with `npm ci`.
Now I everything is working fine.

Thanks for always assisting. 🙏

**Comment by tomalaforge** [comment]
Perfect, that's nice to hear
