### ISSUE TITLE
[Docs] - Translate the rest of the challenges to Spanish

### ISSUE THREAD

**Issue by nelsongutidev** [tomalaforge/angular-challenges#299]
Translate the rest of the missing challenges to spanish

**Comment by nelsongutidev** [comment]
Creating an issue just to document the missing challenges. I have a WIP already @tomalaforge

**Comment by nelsongutidev** [comment]
@tomalaforge If it's ok with you, I'm closing this issue since all challenges without the note on top have been translated

https://github.com/tomalaforge/angular-challenges/pull/374

**Comment by tomalaforge** [comment]
Yes perfect. I really have to find the time to finish this work 😅

And then I'll create a big issue with all translation missing. 

There is one block that you can add inside the translation of projection.md. It was added recently under bonus.
