### ISSUE TITLE
links don't match

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [tomalaforge/angular-challenges#319]
as above https://medium.com/ngconf/deep-dive-into-angular-pipes-c040588cd15d

**Comment by tomalaforge** [comment]
What do you mean ? The link above works for me.

**Comment by michalgrzegorczyk-dev** [comment]
Sorry , I meant the content inside i.e. "This article will also provide the solution for [challenge #8](https://github.com/tomalaforge/angular-challenges/blob/main/apps/pipe-easy/README.md) of Angular Challenges. This challenge has been designed for beginners..."

**Comment by tomalaforge** [comment]
Yes you are right. Thanks a lot for the update. I will correct that
