### ISSUE TITLE
[Docs] New I18n language pt-BR

### ISSUE THREAD

**Issue by kabrunko-dev** [tomalaforge/angular-challenges#399]
Hello, everybody! 👋

I've been thinking if it's possible to add "pt-BR" (i.e. brazilian portuguese) as a new language for the I18n.

I'll be glad to help in the translation. Also, If someone wants to help, please let me know.

I'm suggesting this, because some friends at my work doesn't have a good grasp in English. Likewise, I would dare to say that more people who uses Angular could enjoy the challenges if it was in portuguese. So it would be nice to make these challenges available to more languages.

PS: Sorry for any language/grammar mistake 🙋

Cheers!

**Comment by tomalaforge** [comment]
That's a very good idea. 
@nelsongutidev has already done all the setup for i18n and he is doing the Spanish version. 

So feel free to translate the website in Portuguese.

You can start with the landing page and the how to answer a challenge and with the projection challenge. Then don't translate yet challenge with the warning note on top, I need to rewrite them but I don't have time at the moment. 

Thanks a lot.

**Comment by kabrunko-dev** [comment]
> That's a very good idea. @nelsongutidev has already done all the setup for i18n and he is doing the Spanish version.
> 
> So feel free to translate the website in Portuguese.
> 
> You can start with the landing page and the how to answer a challenge and with the projection challenge. Then don't translate yet challenge with the warning note on top, I need to rewrite them but I don't have time at the moment.
> 
> Thanks a lot.

Hello, @tomalaforge

I'll start as soon as possible the pages you listed. If I get stuck at something, I'll try to reach Nelson since he's also translating the project.

Thanks for the reply and for the chance.

Cheers and good Sunday!

**Comment by nelsongutidev** [comment]
@kabrunko-dev Feel free to reach out if you need help, I'll be glad to help in what I can. Obrigado! :)

**Comment by kabrunko-dev** [comment]
> @kabrunko-dev Feel free to reach out if you need help, I'll be glad to help in what I can. Obrigado! :)

Thank you, Nelson. Also, if you need some help, feel free to contact me. Hasta luego! :smile:
