### ISSUE TITLE
(Challenge 1) Additions to project's code and challenge's doc

### ISSUE THREAD

**Issue by kabrunko-dev** [tomalaforge/angular-challenges#406]
Hi, Thomas :wave: How are you?

I've just finished the first challenge about Projection and I'd like to suggest some additions that I believe it would make a better experience for developers allowing them to focus in the projection side of the challenge.

These considerations are based on some common behaviours among some PRs that I saw during my challenge implementation.

🖥 **Project's code**
- A city service for data access already created
- A city image already in the assets' folder 
  (_There a variety of images in the PRs; the ones listed below matches with the student and teacher image style_)
  - https://github.com/tomalaforge/angular-challenges/pull/343/files#diff-29ee3b110a44bf1d6620c6695a3b32c6d10f525579ee326afc0745ceea86cb79
  - https://github.com/tomalaforge/angular-challenges/pull/376/files#diff-29ee3b110a44bf1d6620c6695a3b32c6d10f525579ee326afc0745ceea86cb79
  - https://github.com/tomalaforge/angular-challenges/pull/384/files#diff-29ee3b110a44bf1d6620c6695a3b32c6d10f525579ee326afc0745ceea86cb79
  - https://github.com/tomalaforge/angular-challenges/pull/125/files#diff-cd0f7d3cc6d0a7e436c8e7760b4603ec153edf2cfc631c053fdd371185d48faa
- Following the other components pattern, move `CardComponent` HTML to the proprierty `template` in the `@Component` decorator

📖 **Challenge's documentation**
- Add a new source for understading or further reading about `ngTemplateOutlet`:
  (_It's because the official documentations (either Angular.io or Angular.dev) doens't help very much as reading some tutorials or your article with the answer_)
  - I'd like to suggest the article ["ngTemplateOutlet: The secret to customisation"](https://angularindepth.com/posts/1405/ngtemplateoutlet) by Stephen Cooper. Also, his talk about typing in `ngTemplateOutlet`: https://www.youtube.com/watch?v=ELRCT7ooNCU. 
  - Likewise two articles of yours about typing: 
    - [NgTemplateOutlet Type Checking](https://medium.com/@thomas.laforge/ngtemplateoutlet-type-checking-5d2dcb07a2c6)
    - [NgTemplateOutlet Typed Checking (Part 2)](https://medium.com/@thomas.laforge/ngtemplateoutlet-typed-checking-part-2-274baa06f83d)
- A section named "A Step Further" (something with this ideia) listing some minichallenges about using some new Angular features like the new control flow syntax (e.g. `@if`, `@for`, `@empty`) and signals for state management, since in some comment of yours, you recommend to use theses features.

What do you think?

Take care and have a nice day :smile:

**Comment by jdegand** [comment]
I agree that there should be a standard city image.  

I'd add Angular 17 handles projection slightly differently.  I think you cannot have nesting solutions.  So you have to careful when using the new control flow with projection.

**Comment by tomalaforge** [comment]
Hi @kabrunko-dev,

Thanks a lot for your feedbacks and all feedbacks are very relevant. I though of adding an image or adding the city store but never done it. So much thing on my plate. 

If you are interested, you can implement them all. 

@jdegand Thanks for the warning, but I tested it on the challenge, and it's working fine, so we can still add it on a follow up section.

**Comment by kabrunko-dev** [comment]
Hello, @tomalaforge

I'd like to do it. And about the image, I'll choose or you have a favorite one?

And @jdegand, thanks for the warning, too! I'll read the PR that you linked.

**Comment by tomalaforge** [comment]
Great 🙏

You can pick the one of your choice. I trust you on this 💪

**Comment by kabrunko-dev** [comment]
@tomalaforge :wave:

PR opened: https://github.com/tomalaforge/angular-challenges/pull/408

**Comment by tomalaforge** [comment]
Done
