### ISSUE TITLE
i18n for shared custom components

### ISSUE THREAD

**Issue by tomalaforge** [tomalaforge/angular-challenges#426]
There is some shared component used in every page, but we need to use a key for i18n instead of a default english phrase. 

The goal of this issue is to prepare the work by creating keys that can be translated afterwards.

**Comment by kabrunko-dev** [comment]
There's tutorials in Astro official doc [here](https://docs.astro.build/en/recipes/i18n/#translate-ui-strings) and also in the Starlight's [here](https://starlight.astro.build/guides/i18n/).

@tomalaforge, would it be in one of these ways or there is another way that you recommend?

**Comment by tomalaforge** [comment]
@kabrunko-dev the translation has already been done by @eduardoRoth

**Comment by kabrunko-dev** [comment]
@tomalaforge nice!
