### ISSUE TITLE
Unify Spanish translations

### ISSUE THREAD

**Issue by ErickRodrCodes** [tomalaforge/angular-challenges#436]
So, we have 3 native Spanish speakers, and we didn't decide the right localization

When I started to do my part of translations, I didn't consider if it should be:
- Iberican Spanish (es-ES) 
- or Latin-American Spanish (es-LA) 
- and now Mexican Spanish (es-MX)

The funny part: all of the Spanish translators (@ErickRodrCodes, @eduardoRoth  and @nelsongutidev ) are Latin-American folks :)

The constrains between ex-MX and es-LA overlaps each other. **My suggestion is to use _ES_ without no localization**, and here is why: we are talking to our community in technical language that is common. the context of the exercises remains intact because the language is very standard, and we don't talk about local lexical context. Example: We know we have to have a "_git fork_" to contribute, but when we translate back to Spanish, there is no way we say "_git tenedor_" because it is technical language.

I read through all the exercises and in my opinion, there is few rooms for specific lexical variation given the kind of language we intend to provide. So, it is better we just leave ES instead breaking up on multiple Spanish localizations.

cc @tomalaforge

**Comment by tomalaforge** [comment]
@ErickRodrCodes 🙏

I was going to ask the question. I don't know anything about the spanish language but when it comes to French. it's the same, we have fr-BE, fr-CA but it's almost identical. 

I think having one locale is great. If in the future. there is thousands of people from different spanish countries that really doesnt' understand this spanish, we can decide to translate it.

But grouping your contribution is better, since you can review each other and have a better translation. 

What do you think @eduardoRoth ? You were the one to switch to es-MX

**Comment by nelsongutidev** [comment]
Agreed @ErickRodrCodes , thanks for bringing it up. Yes, I also believe like @tomalaforge  that one unified locale `ES` is probably best for now.

**Comment by eduardoRoth** [comment]
@ErickRodrCodes @tomalaforge ; I don't have any issues with merging Spanish locales. The reason for me adding one locale is that there're some changes that I would have done to words and sentences in the current Spanish one, and didn't want to just go overriding it alongside my other changes and updates.

I can create a PR to merge Spanish, and handle suggestions in separate PRs from new translations.

**Comment by eduardoRoth** [comment]
Also, this would probably affect Portuguese translation, as right now it's Brazilian one.

**Comment by tomalaforge** [comment]
Yes that's true for portuguese too, but I don't know how different both language are: @kabrunko-dev Do you think having only one locale for portuguese would be enough ?

And you can do the merge @ErickRodrCodes.

**Comment by kabrunko-dev** [comment]
Hello everybody :wave:

@tomalaforge, for me it's okay to use only one locale for now. There's also some differences, but like spanish and french variations in the end we can understand each other.

Also, as you said, " _If in the future. there is thousands of people from different spanish countries that really doesnt' understand this spanish, we can decide to translate it._"

**Comment by tomalaforge** [comment]
ok awesome so we can change the locale to `pt` as well instead of `pt-BR` and say `portuguese` in the menu instead of `brazilian`, is that ok for you ? @kabrunko-dev

**Comment by kabrunko-dev** [comment]
For me it's okay @tomalaforge

**Comment by tomalaforge** [comment]
Done
