### ISSUE TITLE
NgRx Notification directions need clarification

### ISSUE THREAD

**Issue by jdegand** [tomalaforge/angular-challenges#463]
`create an injection token to hide the push service implementation.`  -> Couldn't you just remove the notifications service completely and inject the push service and recreate the `init` method in each store ?  i.e.  When we navigate to any route, the init method will dispatch an event and a new student etc will be added to the list.   This does work but the  notifications will continue when you navigate away from that route.  Notifications for each route should be displayed only when the user is on that route.    

`Option 1: set SchoolStore in root, but we don't want this to separate our class.` ->  This is unclear.  
You can't listen to an action to trigger an effect with the SchoolStore because the SchoolStore uses Component Store.  A Component Store has no actions.   So even if it is set in root, I don't see how that would work.

I used a global effect for a snackbar alert and added a student effect like this 

```
  addStudent$ = createEffect(() =>
    this.actions$.pipe(
      ofType(studentActions.addOneStudent),
      map(action =>
        appActions.showAlert({
          message: "Add 1 Student"
        })
      )
    )
  ); 
```
This causes a snackbar alert with the message.  

I could rewrite the school store to mimic the other stores but that is not the intended fix.

```
 // from school.store

  private readonly loadSchools = this.effect<void>(
    pipe(
      switchMap(() =>
        this.httpService.getAllSchools().pipe(
          tapResponse(
            (schools) => this.patchState({ schools }),
            (_) => _  //  This confused me initially.  Best to add a comment that you don't have to implement error handling ? 
          )
        )
      )
    )
  );
```

The directions could use a mention of Angular Material snackbar since Angular Material is an included dependency.

**Comment by tomalaforge** [comment]
This challenge was my second one and since nobody never took it, I didn't spend time to rewrite the documentation. 

 I'll see if I find some time one day to do it. 
 
 Thanks
