### ISSUE TITLE
Repo size

### ISSUE THREAD

**Issue by jdegand** [tomalaforge/angular-challenges#557]
The size of the repo has doubled in the past few months.  I'd suggest you remove `rx-angular` from dependencies.  Unless you have an `rx-angular` challenge in progess, I'd remove it.   `rx-angular` has 4,000 npm downloads a week.  Niche dependencies like `@ngrx/signals` (7,000 a week) can added per PR.    If you remove rx-angular etc, previous PR could break so you'd  have to add a warning to the docs when checking out a PR with rx-angular or any removed dependency.

**Comment by tomalaforge** [comment]
Thanks for pointing this out, but does it really matter ? The goal is to try out angular and its ecosystem. If one day, those librairies stop me from uprading, i will remove them, but for now, I don't see any issues with them. 
What is your main problem ?

**Comment by jdegand** [comment]
As someone who always runs out of space, I'd prefer less dependencies especially if they aren't really used.

**Comment by tomalaforge** [comment]
Ok I understand. I still prefer to let them right now, because i like playing around with the library and this repo is kind of a playground where I can test and try new features from all librairies. 
But I'll try to avoid adding more lib in the future.

**Comment by tomalaforge** [comment]
stale
