### ISSUE TITLE
Help to start challenges

### ISSUE THREAD

**Issue by rafaelwebrota** [tomalaforge/angular-challenges#731]
I follow the steps in site, but i cant start up a single challenge.
I run npm ci
i installed nx with global scope
i tried run npx nx serve angular-permissions --verbose

and i got this error: 

![image](https://github.com/tomalaforge/angular-challenges/assets/120112046/1fd4b538-5ea3-45d2-9515-4143bd2eb5f7)

I'm using nvm....and tried with ?
v16.12.0
v18.19.0

can anyone help me ?

**Comment by tomalaforge** [comment]
It's hard to say
You need to be node 18.x or 20.x. But if you followed all the steps, I don't know what to say. 
What version of npm do you have ? 
Are you on the latest version of the repository ? 
Try to remove node-module, rm -rf node-modules, update your node version to 20.x and run npm ci again. 
And we will go from here.

**Comment by rafaelwebrota** [comment]
![image](https://github.com/tomalaforge/angular-challenges/assets/120112046/b82d27bc-7b15-43b1-bc1b-b5f55b8b6fa5)

the first print is using 18.x.
The last is using v20.12.1.
And i checked if is the latest version of the repository.
The error in print was when i tried `npm ci`

**Comment by rafaelwebrota** [comment]
Its worked.
i read the log message....i'm newbie.
After rum npm install, and npm ci....
i could start the project.
Thanks for the help.

![image](https://github.com/tomalaforge/angular-challenges/assets/120112046/acb8b5c1-33e3-40ae-859b-0a4e168a2eab)
