### ISSUE TITLE
"forms" option is missing in nx generate schematic UI

### ISSUE THREAD

**Issue by alcaidio** [tomalaforge/angular-challenges#760]
Expected result: to add the option "forms" in the select. See image below

<img width="1432" alt="Capture d’écran 2024-04-10 à 21 07 58" src="https://github.com/tomalaforge/angular-challenges/assets/17033036/857523b4-d73c-4449-b96f-4caff00e3dcf">

**Comment by alcaidio** [comment]
I dont know how to fix this i'm never work with Nx 😅

**Comment by jdegand** [comment]
This can be closed you fixed it.

**Comment by alcaidio** [comment]
Me ? nope i never fix it ??

**Comment by jdegand** [comment]
I guess I should have put @tomalaforge before my comment.  Sorry for any confusion.

**Comment by tomalaforge** [comment]
Fixed
