### ISSUE TITLE
Missing answer label

### ISSUE THREAD

**Issue by svenson95** [tomalaforge/angular-challenges#781]
@tomalaforge can you add the answer label for that PR? currently it's not visible under "Community solutions", i was surprised for a moment because i thought i had already done this challenge 😄

_Originally posted by @svenson95 in https://github.com/tomalaforge/angular-challenges/issues/704#issuecomment-2054012834_

**Comment by tomalaforge** [comment]
indeed, I don't know what happenned, sorry for that
