### ISSUE TITLE
Tailwind Warning in bug signal challenge

### ISSUE THREAD

**Issue by jdegand** [tomalaforge/angular-challenges#857]
Since you didn't actually use any Tailwind styling,  when you run the app, you get a warning in the terminal.   It can be fixed by commenting out the Tailwind styles or removing them.  If you want to delete the Tailwind styles, the Tailwind config can be removed as well.  Of course, a style could added to the form and then the warning will be gone as well.  

Unrelated issue with Tailwind in VSCode, there will be warnings when using `@tailwind` syntax (only seen when user goes to the file).  
In the VSCode `settings.json`, this could be added to eliminate those warnings:

```
"files.associations": {
   "*.scss": "tailwindcss"
}
```

This is really minor stuff, but less confusion for challengers.

**Comment by tomalaforge** [comment]
Ok, I don't have any warnings 😅

**Comment by jdegand** [comment]
Well, have to wait and see if anyone else has these problems and comments here.

**Comment by jdegand** [comment]
The warning is specific to my setup and I did not encounter the error with a configuration change.
