### ISSUE TITLE
(bug) Sponsors link overflow

### ISSUE THREAD

**Issue by jdegand** [tomalaforge/angular-challenges#876]
![sponsors-error](https://github.com/tomalaforge/angular-challenges/assets/70610011/92b2c37b-fa74-47fa-b1e5-6a5e44295ac5)

See the little line next to the second circle that is the link of the first sponsor.

The default styling of a link (`text-decoration:underline`) creates this line.  You are not setting any styling for the link and the link for some reason has a longer width than the image.

**Comment by tomalaforge** [comment]
fixed. Thanks
