### ISSUE TITLE
challenge number in the app project name

### ISSUE THREAD

**Issue by tomalaforge** [tomalaforge/angular-challenges#884]
Should I add the number of the challenge in the app project name ? 

<img width="217" alt="image" src="https://github.com/tomalaforge/angular-challenges/assets/30832608/6bd29697-482e-4ecd-890e-87700aab3ef6">

If you look at the folder, should it be:
- angular 
- 21-anchor-scrolling
- xx-bug-cd
- xx-bug-effect-signal

and so one. 

I don't know how hard is it to find the right challenge ? 

Or maybe it is correct the way it is now 

What do you think ?

**Comment by tomalaforge** [comment]
@jdegand @svenson95 @LMFinney

**Comment by LMFinney** [comment]
I think 21-anchor-scrolling would work. That's what we did at https://github.com/angularbootcamp/abc, when I worked on that.

**Comment by jdegand** [comment]
The eslint forbidden enum 27 challenge is hard to find.  Probably need to update the readme for that challenge to tell challengers to look under `tools`.   No one has completed the challenge.

That challenge is one where the name of challenge doesn't match the filenames as well.  `Custom Eslint Rule` vs `Forbidden Enum`.   There are multiple challenges where this is the case.  

If you add the numbers, I guess the title and filenames don't have to match.  

If you plan on doing a rework, I'd also think about re-categorizing some challenges.  Move `interop` to RxJS category.  `Typed ContextOutlet` (and possibily  `Utility Wrapper Pipe`) to TypeScript.  But then you'd have a lot of work in changing all translation folders as well.

**Comment by LMFinney** [comment]
In addition to re-categorizing, I think some of the difficulty levels could be tweaked. For example, `crud application` wasn't hard for me, but there's a lot more code involved than in the other "easy" ones.

But to @jdegand's point, the difference between "Pure Pipe" and "pipe-easy" is a bit confusing.

**Comment by jdegand** [comment]
It is worse than I thought.  There's at least 15 mismatched challenges.  However, the command in the readme should clue challengers to the filename of the challenge.  

I think it will be signficantly easier to just change the title of the readme to match the existing filename.

This might lead to some ugly titles, but it is a quick fix and it will be less error prone.  You still will have to update all translation checklists in the other issues.

**Comment by svenson95** [comment]
The challenge number would really help to navigate through the challenges. That's a good idea.

Imo it would be great if we could use matching challenge titles & filenames. As @LMFinney already mentioned, the pipe challenge titles and filenames are a bit confusing.

Re-categorizing is a good point as well. The new signal challenges should have a own signal category.

**Comment by tomalaforge** [comment]
thanks a lot for your feedback
I agree with the name should match the title. Very hard to find the right challenge. 
And by adding the number, it will be easier as well. 

I can indeed re-categorize some challenges. 
I will do this in a second step I think.

**Comment by tomalaforge** [comment]
Done
