### ISSUE TITLE
Issues with the new file system

### ISSUE THREAD

**Issue by jdegand** [tomalaforge/angular-challenges#891]
- I didn't think of this earlier, but did the file changes break functionality with pulling past PRs with the GitHub CLI?  Has anyone tried this?  This could be a big problem.  

- `ngrx notification` is in the libs folder whereas challenge is called `7-power of effect`.

- `bug-signal-effect`  vs. `50-bug-signal-effect`.  And `bug-signal-effect` is not in the signal category.  

- Each challenge's `index.html` has the older title.

**Comment by tomalaforge** [comment]
- No, the PR is linked to a branch which will have the old struture. 
- Ok
- waiting for the PR of @svenson95 to be merged
- Nice catch

**Comment by svenson95** [comment]
> * No, the PR is linked to a branch which will have the old struture.
> * Ok
> * waiting for the PR of @svenson95 to be merged
> * Nice catch

PR ready to merge

**Comment by jdegand** [comment]
I think some readme commands need to be updated as well.

**Comment by tomalaforge** [comment]
like which one?

**Comment by jdegand** [comment]
The power of effect command is wrong.  There may be more.

**Comment by tomalaforge** [comment]
no, the readme of 7-power-of-effect is correct.

**Comment by jdegand** [comment]
It must not have been updated (or vercel deployed) when I lasted viewed it.  I looked into the readme and it looked right.
