### ISSUE TITLE
(styling bug)  Light Mode - Heart Missing 

### ISSUE THREAD

**Issue by jdegand** [tomalaforge/angular-challenges#892]
![join-the-list](https://github.com/tomalaforge/angular-challenges/assets/70610011/6f212b9c-50db-4b10-8a4b-e405d3fe76ea)

The heart is always white so on light mode, it is not seen.

**Comment by fixedmichal** [comment]
https://github.com/tomalaforge/angular-challenges/pull/949

**Comment by tomalaforge** [comment]
Thanks @fixedmichal
