### ISSUE TITLE
(styling bug) Github logo in button shouldn't be styled for dark/light mode

### ISSUE THREAD

**Issue by jdegand** [tomalaforge/angular-challenges#893]
![github-button](https://github.com/tomalaforge/angular-challenges/assets/70610011/dffa5084-89bf-49ff-9f01-7b0867ef402c)

Since the background is green, it is best to have the logo stay white in both light and dark mode.

**Comment by Tenessy** [comment]
Hello @tomalaforge , can you assigned me to this task please ?

**Comment by tomalaforge** [comment]
@Tenessy Thanks a lot 🙏
